-- Run once in Supabase SQL editor (replace forensic_patterns if your table name differs).

ALTER TABLE forensic_patterns ADD COLUMN IF NOT EXISTS timeframe_resolution text;
ALTER TABLE forensic_patterns ADD COLUMN IF NOT EXISTS macro_weather_layout text;
ALTER TABLE forensic_patterns ADD COLUMN IF NOT EXISTS execution_strategy text;
ALTER TABLE forensic_patterns ADD COLUMN IF NOT EXISTS buffer_context_window text;
ALTER TABLE forensic_patterns ADD COLUMN IF NOT EXISTS vault_track text DEFAULT 'track_1_validated';
ALTER TABLE forensic_patterns ADD COLUMN IF NOT EXISTS data_feed_mode text DEFAULT 'carousel_15s';
ALTER TABLE forensic_patterns ADD COLUMN IF NOT EXISTS state text DEFAULT 'active';
ALTER TABLE forensic_patterns ADD COLUMN IF NOT EXISTS deleted_at timestamptz;

CREATE TABLE IF NOT EXISTS strategy_executions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker text NOT NULL,
    pattern_category text DEFAULT 'VALIDATED',
    macro_weather_layout text,
    execution_strategy text,
    timeframe_resolution text,
    timeline_key text NOT NULL,
    margin_pct double precision DEFAULT 0,
    recorded_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS strategy_executions_timeline_idx
    ON strategy_executions (timeline_key, recorded_at DESC);
