-- Live TradingView screener hits. Webhook inserts; Room 3 heartbeat reads.
-- Run in Supabase SQL editor.

CREATE TABLE IF NOT EXISTS room3_screener_hits (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker text NOT NULL,
    session text NOT NULL DEFAULT 'rth',
    source text NOT NULL DEFAULT 'tradingview',
    seen_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS room3_screener_hits_session_seen_idx
    ON room3_screener_hits (session, seen_at DESC);

CREATE INDEX IF NOT EXISTS room3_screener_hits_ticker_seen_idx
    ON room3_screener_hits (ticker, seen_at DESC);

ALTER TABLE room3_screener_hits ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS room3_screener_hits_read ON room3_screener_hits;
CREATE POLICY room3_screener_hits_read
    ON room3_screener_hits
    FOR SELECT
    USING (true);

-- Inserts come from the Edge Function (service role bypasses RLS).
